spring.datasource.url=jdbc:postgresql://localhost:5432/db_expedientes
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desativa o aviso do Open-In-View nos logs
spring.jpa.open-in-view=false

# O dialeto já não é necessário no Spring Boot 3+
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect